CC=g++
CFLAGS=-Wall -Wextra -Weffc++ -Wold-style-cast -Woverloaded-virtual -std=c++0x -pedantic -Werror -g

up1: up1.cc
	$(CC) $(CFLAGS) up1.cc -o up1

up2: up2.cc
	$(CC) $(CFLAGS) up2.cc -o up2

up3: up3.cc
	$(CC) $(CFLAGS) up3.cc -o up3

up4: up4.cc
	$(CC) $(CFLAGS) up4.cc -o up4

mega: mega.cc
	$(CC) $(CFLAGS) mega.cc -o mega

clean:
	rm -rf *.o a.out up1 up2 up3 up4 mega *~
